// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Comment struct {
	ID        int        `json:"id"`
	ParentID  *int       `json:"parent_id,omitempty"`
	User      *User      `json:"user"`
	Post      *Post      `json:"post"`
	Text      string     `json:"text"`
	Status    TypeStatus `json:"status"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type CreateCommentInput struct {
	PostID   int    `json:"post_id"`
	ParentID *int   `json:"parent_id,omitempty"`
	Text     string `json:"text"`
}

type CreatePostInput struct {
	Text        string `json:"text"`
	CanHaveComm *bool  `json:"can_have_comm,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Post struct {
	ID          int        `json:"id"`
	User        *User      `json:"user"`
	Text        string     `json:"text"`
	CanHaveComm bool       `json:"can_have_comm"`
	Comments    []*Comment `json:"comments"`
	Status      TypeStatus `json:"status"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

type Subscription struct {
}

type UpdatePostInput struct {
	PostID      int  `json:"post_id"`
	CanHaveComm bool `json:"can_have_comm"`
}

type User struct {
	ID        int        `json:"id"`
	Username  string     `json:"username"`
	Email     string     `json:"email"`
	Posts     []*Post    `json:"posts"`
	Status    TypeStatus `json:"status"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

type TypeStatus string

const (
	TypeStatusActive  TypeStatus = "active"
	TypeStatusBlocked TypeStatus = "blocked"
)

var AllTypeStatus = []TypeStatus{
	TypeStatusActive,
	TypeStatusBlocked,
}

func (e TypeStatus) IsValid() bool {
	switch e {
	case TypeStatusActive, TypeStatusBlocked:
		return true
	}
	return false
}

func (e TypeStatus) String() string {
	return string(e)
}

func (e *TypeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TypeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TypeStatus", str)
	}
	return nil
}

func (e TypeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TypeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TypeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
